# Generated by Django 5.1.3 on 2024-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campsites', '0002_campsite_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
