# Generated by Django 5.1.3 on 2024-12-02 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('campsites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('campsite', 'Campsite Review'), ('booking', 'Booking Review')], default='campsite', max_length=10)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('cleanliness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('campsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_reviews', to='campsites.campsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', True), ('campsite__isnull', False), ('review_type', 'campsite')), models.Q(('booking__isnull', False), ('campsite__isnull', True), ('review_type', 'booking')), _connector='OR'), name='valid_review_type_relation'), models.UniqueConstraint(condition=models.Q(('review_type', 'campsite')), fields=('user', 'campsite'), name='unique_user_campsite_review'), models.UniqueConstraint(condition=models.Q(('review_type', 'booking')), fields=('user', 'booking'), name='unique_user_booking_review')],
            },
        ),
    ]
